name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter Manually
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable ~/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          flutter doctor

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: cam2pdf-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
